- name: system setup | package cleanup | remove unneeded packages (debian, ubuntu, etc)
  tags: cleanup,packages,system,settings
  package:
    state: absent
    name: "{{ item }}"
  with_items: "{{ apt_package_removal }}"
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
