---
- name: Install snapd apt dependency
  become: true
  apt:
    name: "snapd"
    state: present

- name: Install Snaps
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default('stable')}}"
    classic: "{{ item.classic | default('no')}}"
  with_items: "{{ snaps }}"
